### ISSUE TITLE
Remove "Limit to online collections" dropdown option from home page and search page (Wed EOD)

### ISSUE THREAD

**Issue by reliztrent** [gwu-libraries/aspace-pui#29]
On one pages, the homepage and search page (https://searcharchives.library.gwu.edu/search), there is a search form that has a drop down with a default option "Search all record types." The drop down has two other options, one of which should be removed: "Limit to online materials".

**Comment by kerchner** [comment]
May be added back, so just comment out

**Comment by reliztrent** [comment]
1. Comment out lines 25 - 28 of _search.html.erb
2. Add _search.html.erb to "local" plugin at plugins/local/public/views/

See https://github.com/archivesspace/archivesspace/blob/2bce49707d58603b6f4890628290c5b301bb7e0d/public/app/views/shared/_search.html.erb

**Comment by rareleah** [comment]
Hey @reliztrent can you leave the box but just remove "limit to online materials"?

**Comment by lwrubel** [comment]
Fixed by #46
