### ISSUE TITLE
Add an indication of how to request materials (Wed EOD)

### ISSUE THREAD

**Issue by reliztrent** [gwu-libraries/aspace-pui#30]
Either: 
1. implement the "request" button that comes with the PUI

2. add a static message linking to the contact form, at the top of all pages of type: resource or archival_object

**Comment by reliztrent** [comment]
Some potential methods:

1. Add a static message at the top of all pages, as html. 

Add html message that shows up at the top of _all_ pages (records, search results, home page, etc.)

Edit the shared layout file (public/app/views/layouts/application.html.erb) above line 52 ("flash messages") to insert a static message that indicates "To request boxes, please submit the collection, series, and box number(s) via our <a href="https://library.gwu.edu/scrc/contact">Contact form</a>." Or similar (SPEC team will have input on particular wording).


2. Use the "Request" button that's currently suppressed. 

Un-suppress the button in line ## of config.rb

Edit the config button file (public/app/views/shared/_request_page_action.html.erb) so that the button doesn't generate an email, but instead sends the user to https://library.gwu.edu/scrc/contact so that the form is partially pre-filled:
- Type of Request: Request specific materials for on-site use
- Comments: "This request was initiated from record [we'd insert the URL from which the button was pressed]."


3. Configure and use the "Request" button as intended. 

We haven't tested this at all, but it's done via the config.rb file. That file is intending to be self-documenting. Look in file for "request_email" and "pui_requests"

**Comment by reliztrent** [comment]
Leah is ok with all three options above, and prefers option #1

**Comment by maxstarkenburg** [comment]
Noting that current implementation as of yesterday evening was to add the static message with the link to the contact page on libsite via `application.html.erb` override, suppress it by default with CSS, then turn it back on via `/assets/js/gw-scripts.js` for pages with `/resources/`, `/archival_objects/`, and `/top_containers/` in the URL.

I forgot about the possibility of trying to pre-fill some of the form on libsite with values from the aspace page where the link was clicked. Not sure how easy that would be on the Drupal side of things. Don't know if this issue should be left open for trying to implement that, or perhaps make a new cleaner/limited issue?

**Comment by reliztrent** [comment]
We can open a new ticket for improvements.
