### ISSUE TITLE
Knowledge/documentation transfer (weeklong)

### ISSUE THREAD

**Issue by reliztrent** [gwu-libraries/aspace-pui#34]
Catch STG up on:
1. ASpace technical documentation
2. Current requests/issues
3. Upcoming migrations
4. History/ past projects
5. What else?

**Comment by reliztrent** [comment]
See https://docs.google.com/document/d/1aVoYSnogrUwdE4hi-HZK4q2iXDbjO-cFfPeO6xHtOtw/edit#heading=h.yryr6362goxb

**Comment by lwrubel** [comment]
Includes documentation in #43 .

**Comment by reliztrent** [comment]
Work in scope for implementation sprint completed.
