### ISSUE TITLE
Investigate options to speed up "print" PDF option of collection inventory (can it not be generated on the fly?) (Wed EOD)

### ISSUE THREAD

**Issue by rareleah** [gwu-libraries/aspace-pui#35]
Within a collection record the option to print is either timing out or taking a long time (just not took 7 minutes) to generate a PDF.
No error message and it did finally generate a PDF.
Here's the record I was using: https://searcharchives.library.gwu.edu/repositories/2/resources/349

**Comment by reliztrent** [comment]
From config.rb:

```
## The number of PDFs we'll generate (in the background) at the same time.
##
## PDF generation can be a little memory intensive for large collections, so we
## set this fairly low out of the box.
#AppConfig[:pui_max_concurrent_pdfs] = 2
## You can set this to nil or zero to prevent a timeout
#AppConfig[:pui_pdf_timeout] = 600
```

**Comment by reliztrent** [comment]
Wait to implement until review with sys admin & possibly wrap into future performance tuning sprint.
