### ISSUE TITLE
Link forwarders: implement redirects from old XML finding aids to new ASpace records (Fri 9am meeting)

### ISSUE THREAD

**Issue by reliztrent** [gwu-libraries/aspace-pui#39]

**Comment by reliztrent** [comment]
809 redirects prepped at https://docs.google.com/spreadsheets/d/1s94MVhnlfx4RYeMyRsIm4yLUDZuEzPer4LY1rnW8NOA/edit#gid=0

see #6

**Comment by reliztrent** [comment]
Multiple Apache config files, need to check which one to edit in advance, and coordinate with web team.

**Comment by kerchner** [comment]
- [x] Redirect statements created in Google Sheet
- [x] Redirects deployed to test.library.gwu.edu , they work

**Comment by reliztrent** [comment]
Done, tested
